// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"

	net "net"

	nethttp "net/http"
)

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

// ApiRoutes provides a mock function with given fields:
func (_m *Server) ApiRoutes() gin.IRouter {
	ret := _m.Called()

	var r0 gin.IRouter
	if rf, ok := ret.Get(0).(func() gin.IRouter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.IRouter)
		}
	}

	return r0
}

// Listen provides a mock function with given fields: _a0
func (_m *Server) Listen(_a0 net.Listener) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(net.Listener) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServeHTTP provides a mock function with given fields: _a0, _a1
func (_m *Server) ServeHTTP(_a0 nethttp.ResponseWriter, _a1 *nethttp.Request) {
	_m.Called(_a0, _a1)
}
