// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"

	net "net"

	nethttp "net/http"
)

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

// APIRoutes provides a mock function with given fields:
func (_m *Server) APIRoutes() gin.IRouter {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for APIRoutes")
	}

	var r0 gin.IRouter
	if rf, ok := ret.Get(0).(func() gin.IRouter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.IRouter)
		}
	}

	return r0
}

// Listen provides a mock function with given fields: _a0
func (_m *Server) Listen(_a0 net.Listener) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Listen")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(net.Listener) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServeHTTP provides a mock function with given fields: _a0, _a1
func (_m *Server) ServeHTTP(_a0 nethttp.ResponseWriter, _a1 *nethttp.Request) {
	_m.Called(_a0, _a1)
}

// NewServer creates a new instance of Server. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Server {
	mock := &Server{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
