linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - "$all"
          - "!$test"
        allow:
          - $gostd
          - github.com/DATA-DOG/go-sqlmock
          - github.com/dgrijalva/jwt-go
          - github.com/gin-gonic/gin
          - github.com/go-openapi/errors
          - github.com/go-playground/validator/v10
          - github.com/go-redis/redis
          - github.com/grpc-ecosystem/go-grpc-middleware/
          - github.com/grpc-ecosystem/go-grpc-prometheus
          - github.com/jmoiron/sqlx
          - github.com/mitchellh/mapstructure
          - github.com/rs/zerolog
          - github.com/soheilhy/cmux
          - github.com/spf13/pflag
          - github.com/spf13/viper
          - github.com/nojyerac/go-lib
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: use zerolog instead
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - wrapperFunc
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - octalLiteral
  gocyclo:
    min-complexity: 15
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
  lll:
    line-length: 120
  misspell:
    locale: US
  revive:
    rules:
    - name: dot-imports
      disabled: True
linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - ginkgolinter
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  # don't enable:
  # - deadcode
  # - gochecknoglobals
  # - gocognit
  # - godox
  # - prealloc
  # - varcheck
  # - structcheck
