packages:
  github.com/nojyerac/go-lib/db:
    config:
      with-expecter: True
      resolve-type-alias: False
      issue-845-fix: True
      dir: "./mocks/db"
      include-regex: "^(Database|Tx)$"
  github.com/nojyerac/go-lib/health:
    config:
      with-expecter: True
      resolve-type-alias: False
      issue-845-fix: True
      dir: "./mocks/health"
      include-regex: "Checker"
  github.com/nojyerac/go-lib/transport/http:
