packages:
  github.com/nojyerac/go-lib:
    config:
      recursive: True
      keeptree: True
      with-expecter: True
      resolve-type-alias: False
      issue-845-fix: True
      include-regex: "^(Server|Client|Database|Tx|Checker)$"
