---
stages:
  - test

ginkgo:
  stage: test
  image: $CI_REGISTRY/infra/go-builder:latest
  script:
    - ginkgo -r -cover
    - mkdir -p reports && find . -type f -regex '.*\(report.xml\|coverprofile\)$' | while read fn; do mv $fn reports/$(echo $fn | sed -e 's#^\./##' -e 's#/#-#g'); done
  artifacts:
    paths:
      - reports/*.coverprofile
    reports:
      junit: reports/*report.xml

lint:
  stage: test
  image: $CI_REGISTRY/infra/go-builder:latest
  script:
    - golangci-lint run -c .golangci.yml