// Code generated by mockery v2.53.6. DO NOT EDIT.

package http

import (
	net "net"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

type MockServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServer) EXPECT() *MockServer_Expecter {
	return &MockServer_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: pattern, handler
func (_m *MockServer) Handle(pattern string, handler http.Handler) {
	_m.Called(pattern, handler)
}

// MockServer_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockServer_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - pattern string
//   - handler http.Handler
func (_e *MockServer_Expecter) Handle(pattern interface{}, handler interface{}) *MockServer_Handle_Call {
	return &MockServer_Handle_Call{Call: _e.mock.On("Handle", pattern, handler)}
}

func (_c *MockServer_Handle_Call) Run(run func(pattern string, handler http.Handler)) *MockServer_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(http.Handler))
	})
	return _c
}

func (_c *MockServer_Handle_Call) Return() *MockServer_Handle_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServer_Handle_Call) RunAndReturn(run func(string, http.Handler)) *MockServer_Handle_Call {
	_c.Run(run)
	return _c
}

// HandleFunc provides a mock function with given fields: pattern, handler
func (_m *MockServer) HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request)) {
	_m.Called(pattern, handler)
}

// MockServer_HandleFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleFunc'
type MockServer_HandleFunc_Call struct {
	*mock.Call
}

// HandleFunc is a helper method to define mock.On call
//   - pattern string
//   - handler func(http.ResponseWriter , *http.Request)
func (_e *MockServer_Expecter) HandleFunc(pattern interface{}, handler interface{}) *MockServer_HandleFunc_Call {
	return &MockServer_HandleFunc_Call{Call: _e.mock.On("HandleFunc", pattern, handler)}
}

func (_c *MockServer_HandleFunc_Call) Run(run func(pattern string, handler func(http.ResponseWriter, *http.Request))) *MockServer_HandleFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(func(http.ResponseWriter, *http.Request)))
	})
	return _c
}

func (_c *MockServer_HandleFunc_Call) Return() *MockServer_HandleFunc_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServer_HandleFunc_Call) RunAndReturn(run func(string, func(http.ResponseWriter, *http.Request))) *MockServer_HandleFunc_Call {
	_c.Run(run)
	return _c
}

// Listen provides a mock function with given fields: _a0
func (_m *MockServer) Listen(_a0 net.Listener) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Listen")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(net.Listener) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServer_Listen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Listen'
type MockServer_Listen_Call struct {
	*mock.Call
}

// Listen is a helper method to define mock.On call
//   - _a0 net.Listener
func (_e *MockServer_Expecter) Listen(_a0 interface{}) *MockServer_Listen_Call {
	return &MockServer_Listen_Call{Call: _e.mock.On("Listen", _a0)}
}

func (_c *MockServer_Listen_Call) Run(run func(_a0 net.Listener)) *MockServer_Listen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(net.Listener))
	})
	return _c
}

func (_c *MockServer_Listen_Call) Return(_a0 error) *MockServer_Listen_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServer_Listen_Call) RunAndReturn(run func(net.Listener) error) *MockServer_Listen_Call {
	_c.Call.Return(run)
	return _c
}

// ListenAndServe provides a mock function with given fields: addr
func (_m *MockServer) ListenAndServe(addr string) error {
	ret := _m.Called(addr)

	if len(ret) == 0 {
		panic("no return value specified for ListenAndServe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(addr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServer_ListenAndServe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenAndServe'
type MockServer_ListenAndServe_Call struct {
	*mock.Call
}

// ListenAndServe is a helper method to define mock.On call
//   - addr string
func (_e *MockServer_Expecter) ListenAndServe(addr interface{}) *MockServer_ListenAndServe_Call {
	return &MockServer_ListenAndServe_Call{Call: _e.mock.On("ListenAndServe", addr)}
}

func (_c *MockServer_ListenAndServe_Call) Run(run func(addr string)) *MockServer_ListenAndServe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockServer_ListenAndServe_Call) Return(_a0 error) *MockServer_ListenAndServe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServer_ListenAndServe_Call) RunAndReturn(run func(string) error) *MockServer_ListenAndServe_Call {
	_c.Call.Return(run)
	return _c
}

// ServeHTTP provides a mock function with given fields: _a0, _a1
func (_m *MockServer) ServeHTTP(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// MockServer_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type MockServer_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - _a0 http.ResponseWriter
//   - _a1 *http.Request
func (_e *MockServer_Expecter) ServeHTTP(_a0 interface{}, _a1 interface{}) *MockServer_ServeHTTP_Call {
	return &MockServer_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", _a0, _a1)}
}

func (_c *MockServer_ServeHTTP_Call) Run(run func(_a0 http.ResponseWriter, _a1 *http.Request)) *MockServer_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MockServer_ServeHTTP_Call) Return() *MockServer_ServeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServer_ServeHTTP_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *MockServer_ServeHTTP_Call {
	_c.Run(run)
	return _c
}

// NewMockServer creates a new instance of MockServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServer {
	mock := &MockServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
