// Code generated by mockery v2.53.6. DO NOT EDIT.

package health

import (
	context "context"

	health "github.com/nojyerac/go-lib/health"
	mock "github.com/stretchr/testify/mock"
)

// MockChecker is an autogenerated mock type for the Checker type
type MockChecker struct {
	mock.Mock
}

type MockChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChecker) EXPECT() *MockChecker_Expecter {
	return &MockChecker_Expecter{mock: &_m.Mock}
}

// Passed provides a mock function with no fields
func (_m *MockChecker) Passed() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Passed")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockChecker_Passed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Passed'
type MockChecker_Passed_Call struct {
	*mock.Call
}

// Passed is a helper method to define mock.On call
func (_e *MockChecker_Expecter) Passed() *MockChecker_Passed_Call {
	return &MockChecker_Passed_Call{Call: _e.mock.On("Passed")}
}

func (_c *MockChecker_Passed_Call) Run(run func()) *MockChecker_Passed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChecker_Passed_Call) Return(_a0 bool) *MockChecker_Passed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChecker_Passed_Call) RunAndReturn(run func() bool) *MockChecker_Passed_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: _a0, _a1
func (_m *MockChecker) Register(_a0 string, _a1 health.CheckFn) {
	_m.Called(_a0, _a1)
}

// MockChecker_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockChecker_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - _a0 string
//   - _a1 health.CheckFn
func (_e *MockChecker_Expecter) Register(_a0 interface{}, _a1 interface{}) *MockChecker_Register_Call {
	return &MockChecker_Register_Call{Call: _e.mock.On("Register", _a0, _a1)}
}

func (_c *MockChecker_Register_Call) Run(run func(_a0 string, _a1 health.CheckFn)) *MockChecker_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(health.CheckFn))
	})
	return _c
}

func (_c *MockChecker_Register_Call) Return() *MockChecker_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChecker_Register_Call) RunAndReturn(run func(string, health.CheckFn)) *MockChecker_Register_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function with given fields: _a0
func (_m *MockChecker) Start(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChecker_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockChecker_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockChecker_Expecter) Start(_a0 interface{}) *MockChecker_Start_Call {
	return &MockChecker_Start_Call{Call: _e.mock.On("Start", _a0)}
}

func (_c *MockChecker_Start_Call) Run(run func(_a0 context.Context)) *MockChecker_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockChecker_Start_Call) Return(_a0 error) *MockChecker_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChecker_Start_Call) RunAndReturn(run func(context.Context) error) *MockChecker_Start_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function with no fields
func (_m *MockChecker) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockChecker_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockChecker_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockChecker_Expecter) String() *MockChecker_String_Call {
	return &MockChecker_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockChecker_String_Call) Run(run func()) *MockChecker_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChecker_String_Call) Return(_a0 string) *MockChecker_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChecker_String_Call) RunAndReturn(run func() string) *MockChecker_String_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChecker creates a new instance of MockChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChecker {
	mock := &MockChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
